### ISSUE TITLE
帮下忙

### ISSUE THREAD

**Issue by xiangweijun** [niarehtni/helloworld#1]
您好，我看到您的仓库里克隆了几个我仓库相关的代码，这些是公司内部代码，我不小心上传到错了仓库，能否帮忙删除
万分感谢！！！
这是我的联系方式：xwjunself@163.com

**Comment by niarehtni** [comment]
哪个?

**Comment by xiangweijun** [comment]
loan-h5
operation-backend
shouqianba-msp-portal
shouqianba-osp-portal
wosai-native
sales-system-web
node-hongbao

**Comment by niarehtni** [comment]
好的, 我邮件收到了, 今天比较晚了, 我找个时间都删了

**Comment by xiangweijun** [comment]
谢谢
